### ISSUE TITLE
Singing doesn't seem to be working

### ISSUE THREAD

**Issue by sirnewton01** [exploser/sam#1]
This is a cool library because it doesn't require any internet connection to work and it written in Go. :)

I tried one of the demos and it doesn't seem to working. Most of the other demos I tried were working fine.

If you run this command on Mac:
```
sam -sing -speed 40 -pitch 64 -phonetic ohohoh
```

It returns right away without any output to the speaker. Exit code is 2 when I echo $?.

When I run with the debug flag. I get this output.

```
phonetic input: ohohoh
```

Again, no sound.

**Comment by vasilevp** [comment]
Yep, seems to be an issue with how phonetic input is handled. I'll look into it

**Comment by vasilevp** [comment]
That should do it.
Have fun!
